### PR TITLE
change repo link in `pubspec.yaml`

### PR DESCRIPTION
**Pull request by AviAvinav**
updated the the repo link in the pubspec

for issue https://github.com/osociety/network_tools/issues/65

### CODE REVIEW

**Comment by guyluz11** [comment]
Hi @AviAvinav two things.

Please comment on the issue that you would like to work on it (just for it to be organized).

Secondly please re-open/ change pr to dev branch.

Thanks

**Comment by AviAvinav** [comment]
Oh, really sorry about that, I will keep it in mind next time

**Comment by AviAvinav** [comment]
changed to dev branch, sorry about the previous mistake

**Comment by AviAvinav** [comment]
should I close this one and open another pr, since, this one seems to be adding the `main` branch commits into `dev` too

**Comment by guyluz11** [comment]
> should I close this one and open another pr, since, this one seems to be adding the `main` branch commits into `dev` too

That sounds good

**Comment by AviAvinav** [comment]
okay

**Pull request closed without merging**
